export type ErrorCodes = (typeof ErrorCodes)[keyof typeof ErrorCodes];

export const ErrorCodes = {
    UNHANDLED_EXCEPTION: 'UNHANDLED_EXCEPTION',
    EMAIL_MISMATCH: 'EMAIL_MISMATCH',
    EMAILSHA256_MISMATCH: 'EMAILSHA256_MISMATCH',
    API_CLIENT_ERROR: 'API_CLIENT_ERROR',
    AUDIENCE_MANAGER_ERROR: 'AUDIENCE_MANAGER_ERROR',
    BATCH_UPLOADER_ERROR: 'BATCH_UPLOADER_ERROR',
    CONSENT_ERROR: 'CONSENT_ERROR',
    ECOMMERCE_ERROR: 'ECOMMERCE_ERROR',
    EVENTS_ERROR: 'EVENTS_ERROR',
    FORWARDERS_ERROR: 'FORWARDERS_ERROR',
    HELPERS_CALLBACK_ERROR: 'HELPERS_CALLBACK_ERROR',
    HELPERS_XHR_ERROR: 'HELPERS_XHR_ERROR',
    IDENTITY_ERROR: 'IDENTITY_ERROR',
    IDENTITY_API_CLIENT_ERROR: 'IDENTITY_API_CLIENT_ERROR',
    KIT_BLOCKING: 'KIT_BLOCKING',
    PERSISTENCE_ERROR: 'PERSISTENCE_ERROR',
    ROKT_MANAGER: 'ROKT_MANAGER',
    STORE: 'STORE_ERROR',
    VAULT_ERROR: 'VAULT_ERROR',
} as const;