version: 2
updates:
    - package-ecosystem: npm
      directory: '/'
      schedule:
          interval: weekly
          day: 'sunday'
      target-branch: 'chore/dependabot'
      labels: ['dependabot', 'dependencies']
      open-pull-requests-limit: 10
      commit-message:
          prefix: 'chore'
      allow:
          - dependency-type: 'production'

    - package-ecosystem: npm
      directory: 'kits/amplitude/amplitude-8'
      schedule:
          interval: weekly
          day: 'sunday'
      target-branch: 'chore/dependabot'
      labels: ['dependabot', 'dependencies', 'kit']
      open-pull-requests-limit: 5
      commit-message:
          prefix: 'chore'
      allow:
          - dependency-type: 'production'
