coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

flags:
  core:
    paths:
      - src/
  rokt-kit:
    paths:
      - kits/rokt/src/
